services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: unified-interview-piston
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./piston-data:/piston
    restart: unless-stopped
