import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { z } from 'zod';
import { Meeting } from '../models/Meeting.js';
import { MeetingMember } from '../models/MeetingMember.js';
import { SharedFile } from '../models/SharedFile.js';

const uploadInput = z.object({ name: z.string().trim().min(1).max(180), mimeType: z.string().trim().min(1).max(120), contentBase64: z.string().min(1) });
const uploadsDir = path.resolve(process.cwd(), 'uploads');
async function access(meetingCode, userId) { const meeting = await Meeting.findOne({ meetingCode, deletedAt: null }).lean(); if (!meeting) return null; const member = await MeetingMember.findOne({ meetingId: meeting._id, userId, membershipStatus: 'approved', participantStatus: { $nin: ['REMOVED', 'BANNED'] } }).lean(); return member ? { meeting, member } : null; }
function canUpload(member) { return ['host', 'interviewer'].includes(member.role) || member.permissions?.files === true || member.permissions?.canUploadFiles === true; }
export async function listFiles(req, res, next) { try { const context = await access(req.params.meetingCode, req.user._id); if (!context) return res.status(403).json({ message: 'Meeting approval is required.' }); const files = await SharedFile.find({ meetingId: context.meeting._id }).populate('uploadedBy', 'name').sort({ createdAt: -1 }).lean(); res.json({ canUpload: canUpload(context.member) && context.meeting.settings?.fileShareEnabled !== false && ['LIVE', 'PAUSED'].includes(context.meeting.status), files: files.map(file => ({ id: file._id, name: file.originalName, mimeType: file.mimeType, size: file.size, uploadedBy: file.uploadedBy?.name ?? 'Participant', createdAt: file.createdAt })) }); } catch (error) { next(error); } }
export async function uploadFile(req, res, next) { try { const input = uploadInput.parse(req.body); const context = await access(req.params.meetingCode, req.user._id); if (!context) return res.status(403).json({ message: 'Meeting approval is required.' }); if (!['LIVE', 'PAUSED'].includes(context.meeting.status)) return res.status(409).json({ message: 'Files can be uploaded only while the meeting is active.' }); if (context.meeting.settings?.fileShareEnabled === false || !canUpload(context.member)) return res.status(403).json({ message: 'File uploading is disabled by the host.' }); const bytes = Buffer.from(input.contentBase64, 'base64'); if (!bytes.length || bytes.length > 8 * 1024 * 1024) return res.status(400).json({ message: 'Files must be between 1 byte and 8 MB.' }); const storedName = `${crypto.randomUUID()}${path.extname(input.name).slice(0, 12).toLowerCase()}`; await fs.mkdir(uploadsDir, { recursive: true }); await fs.writeFile(path.join(uploadsDir, storedName), bytes, { flag: 'wx' }); const file = await SharedFile.create({ meetingId: context.meeting._id, uploadedBy: req.user._id, originalName: path.basename(input.name), storedName, mimeType: input.mimeType, size: bytes.length }); res.status(201).json({ file: { id: file._id, name: file.originalName, mimeType: file.mimeType, size: file.size } }); } catch (error) { next(error); } }
export async function downloadFile(req, res, next) { try { const context = await access(req.params.meetingCode, req.user._id); if (!context) return res.status(403).json({ message: 'Meeting approval is required.' }); const file = await SharedFile.findOne({ _id: req.params.fileId, meetingId: context.meeting._id }).lean(); if (!file) return res.status(404).json({ message: 'File not found.' }); res.download(path.join(uploadsDir, file.storedName), file.originalName); } catch (error) { next(error); } }
