import { z } from 'zod';
import { Meeting } from '../models/Meeting.js';
import { MeetingMember } from '../models/MeetingMember.js';
import { Problem } from '../models/Problem.js';
import { TestCase } from '../models/TestCase.js';
import { Submission } from '../models/Submission.js';
import { executeInSandbox } from '../services/codeExecutionService.js';

const testCaseInput = z.object({ input: z.string().max(50000), expectedOutput: z.string().max(50000), isHidden: z.boolean().default(false), weight: z.number().min(0).max(100).default(1) });
const createInput = z.object({ title: z.string().trim().min(3).max(180), statement: z.string().min(5).max(20000), constraints: z.string().max(5000).optional().default(''), inputFormat: z.string().max(3000).optional().default(''), outputFormat: z.string().max(3000).optional().default(''), allowedLanguages: z.array(z.enum(['javascript', 'python', 'cpp'])).min(1).max(3), timeLimitSec: z.number().int().min(60).max(14400), testCases: z.array(testCaseInput).min(1).max(50) });

async function context(meetingCode, userId) { const meeting = await Meeting.findOne({ meetingCode, type: 'technical_interview', deletedAt: null }); if (!meeting) return { meeting: null, member: null }; const member = await MeetingMember.findOne({ meetingId: meeting._id, userId, membershipStatus: 'approved' }); return { meeting, member }; }
function host(member) { return member?.role === 'host' || member?.role === 'interviewer'; }
export async function listProblems(req, res, next) { try { const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' }); if (!host(member) && !meeting.technical?.problemVisible) return res.json({ problems: [], hidden: true }); const problems = await Problem.find({ meetingId: meeting._id }).sort({ order: 1, createdAt: 1 }).lean(); res.json({ problems: problems.map(problem => ({ id: problem._id, title: problem.title, timeLimitSec: problem.timeLimitSec, allowedLanguages: problem.allowedLanguages, order: problem.order })) }); } catch (error) { next(error); } }
export async function getProblem(req, res, next) { try { const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' }); if (!host(member) && !meeting.technical?.problemVisible) return res.status(403).json({ message: 'The interviewer has not revealed this problem yet.' }); const problem = await Problem.findOne({ _id: req.params.problemId, meetingId: meeting._id }).lean(); if (!problem) return res.status(404).json({ message: 'Problem not found.' }); const cases = await TestCase.find({ problemId: problem._id, ...(host(member) ? {} : { isHidden: false }) }).sort({ order: 1 }).lean(); res.json({ problem: { id: problem._id, title: problem.title, statement: problem.statement, constraints: problem.constraints, inputFormat: problem.inputFormat, outputFormat: problem.outputFormat, timeLimitSec: problem.timeLimitSec, allowedLanguages: problem.allowedLanguages }, testCases: cases.map(testCase => ({ id: testCase._id, input: testCase.input, expectedOutput: testCase.expectedOutput, isHidden: testCase.isHidden, weight: testCase.weight })) }); } catch (error) { next(error); } }
export async function createProblem(req, res, next) { try { const input = createInput.parse(req.body); const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!host(member)) return res.status(403).json({ message: 'Interviewer permission required.' }); if (['ENDED', 'CANCELLED', 'EXPIRED'].includes(meeting.status)) return res.status(409).json({ message: 'Problems cannot be added to a closed interview.' }); const order = await Problem.countDocuments({ meetingId: meeting._id }); const problem = await Problem.create({ ...input, testCases: undefined, meetingId: meeting._id, order, createdBy: req.user._id }); await TestCase.insertMany(input.testCases.map((testCase, index) => ({ ...testCase, problemId: problem._id, order: index }))); meeting.technical.durationSec = input.timeLimitSec; meeting.technical.problemVisible = false; await meeting.save(); res.status(201).json({ problem: { id: problem._id, title: problem.title } }); } catch (error) { next(error); } }

const executionInput = z.object({ language: z.enum(['javascript', 'python', 'cpp']), sourceCode: z.string().min(1).max(100000), action: z.enum(['run', 'submit']) });
const normalize = (value) => String(value ?? '').replace(/\r\n/g, '\n').trimEnd();
export async function executeProblem(req, res, next) { try {
  const input = executionInput.parse(req.body); const { meeting, member } = await context(req.params.meetingCode, req.user._id);
  if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' });
  if (!['LIVE', 'PAUSED'].includes(meeting.status)) return res.status(409).json({ message: 'Code can be executed only during an active interview.' });
  if (!host(member) && !meeting.technical?.problemVisible) return res.status(403).json({ message: 'The interviewer has not revealed this problem yet.' });
  if (!host(member) && !meeting.technical?.candidateStartedAt) return res.status(409).json({ message: 'Click Start coding before running or submitting code.' });
  if (!host(member) && meeting.technical?.candidateStartedAt && Date.now() >= new Date(meeting.technical.candidateStartedAt).getTime() + (meeting.technical.durationSec ?? 0) * 1000) return res.status(410).json({ message: 'The coding time limit has ended.' });
  const problem = await Problem.findOne({ _id: req.params.problemId, meetingId: meeting._id }); if (!problem) return res.status(404).json({ message: 'Problem not found.' });
  if (!problem.allowedLanguages.includes(input.language)) return res.status(400).json({ message: 'This language is not allowed for the problem.' });
  const tests = await TestCase.find({ problemId: problem._id, ...(input.action === 'run' ? { isHidden: false } : {}) }).sort({ order: 1 }).lean();
  const results = []; for (const testCase of tests) { const run = await executeInSandbox({ language: input.language, sourceCode: input.sourceCode, stdin: testCase.input }); results.push({ passed: !run.compileError && !run.stderr && normalize(run.stdout) === normalize(testCase.expectedOutput), run, sample: !testCase.isHidden, expectedOutput: testCase.expectedOutput }); }
  const passed = results.filter(result => result.passed).length; const firstFailure = results.find(result => !result.passed); const submission = await Submission.create({ meetingId: meeting._id, problemId: problem._id, candidateId: req.user._id, language: input.language, sourceCode: input.sourceCode, action: input.action, status: firstFailure?.run.compileError || firstFailure?.run.stderr ? 'failed' : 'completed', testSummary: { passed, total: tests.length }, visibleResult: firstFailure ? { stdout: firstFailure.run.stdout, stderr: firstFailure.run.stderr, compileError: firstFailure.run.compileError, runtimeMs: firstFailure.run.runtimeMs } : {}, completedAt: new Date() });
  res.json({ submissionId: submission._id, status: submission.status, summary: { passed, total: tests.length }, results: input.action === 'run' ? results.filter(result => result.sample).map(result => ({ passed: result.passed, stdout: result.run.stdout, stderr: result.run.stderr, compileError: result.run.compileError, expectedOutput: result.expectedOutput })) : undefined, feedback: input.action === 'submit' && firstFailure ? (firstFailure.run.compileError || firstFailure.run.stderr ? 'Your code could not run. Fix the displayed code error and submit again.' : 'Some hidden test cases did not pass.') : undefined });
} catch (error) { next(error); } }
