import { z } from 'zod';
import { Meeting } from '../models/Meeting.js';
import { MeetingMember } from '../models/MeetingMember.js';
import { Problem } from '../models/Problem.js';
import { TestCase } from '../models/TestCase.js';
import { Submission } from '../models/Submission.js';
import { CandidateDraft } from '../models/CandidateDraft.js';
import { executeInSandbox } from '../services/codeExecutionService.js';
import { asyncHandler } from '../utils/asyncHandler.js';

const testCaseInput = z.object({ input: z.string().max(50000), expectedOutput: z.string().max(50000), isHidden: z.boolean().default(false) });
const createInput = z.object({ title: z.string().trim().min(3).max(180), statement: z.string().min(5).max(20000), constraints: z.string().max(5000).optional().default(''), inputFormat: z.string().max(3000).optional().default(''), outputFormat: z.string().max(3000).optional().default(''), allowedLanguages: z.array(z.enum(['javascript', 'python', 'cpp'])).min(1).max(3), timeLimitSec: z.number().int().min(60).max(14400), testCases: z.array(testCaseInput).min(1).max(50) });

async function context(meetingCode, userId) { const meeting = await Meeting.findOne({ meetingCode, type: 'technical_interview', deletedAt: null }); if (!meeting) return { meeting: null, member: null }; const member = await MeetingMember.findOne({ meetingId: meeting._id, userId, membershipStatus: 'approved' }); return { meeting, member }; }
function host(member) { return member?.role === 'host' || member?.role === 'interviewer'; }
export const listProblems = asyncHandler(async (req, res) => { const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' }); if (!host(member) && (!meeting.technical?.problemVisible || meeting.technical?.candidateId?.toString() !== req.user._id.toString())) return res.json({ problems: [], hidden: true }); const problems = await Problem.find({ meetingId: meeting._id }).sort({ order: 1, createdAt: 1 }).lean(); const submitted = meeting.technical?.candidateId ? await Submission.distinct('problemId', { meetingId: meeting._id, candidateId: meeting.technical.candidateId, action: 'submit' }) : []; const submittedIds = new Set(submitted.map(String)); res.json({ problems: problems.map(problem => ({ id: problem._id, title: problem.title, timeLimitSec: problem.timeLimitSec, allowedLanguages: problem.allowedLanguages, order: problem.order, submitted: submittedIds.has(String(problem._id)) })) }); });
export const getProblem = asyncHandler(async (req, res) => { const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' }); if (!host(member) && (!meeting.technical?.problemVisible || meeting.technical?.candidateId?.toString() !== req.user._id.toString())) return res.status(403).json({ message: 'This problem is available only to the selected candidate after coding starts.' }); const problem = await Problem.findOne({ _id: req.params.problemId, meetingId: meeting._id }).lean(); if (!problem) return res.status(404).json({ message: 'Problem not found.' }); const cases = await TestCase.find({ problemId: problem._id, ...(host(member) ? {} : { isHidden: false }) }).sort({ order: 1 }).lean(); res.json({ problem: { id: problem._id, title: problem.title, statement: problem.statement, constraints: problem.constraints, inputFormat: problem.inputFormat, outputFormat: problem.outputFormat, timeLimitSec: problem.timeLimitSec, allowedLanguages: problem.allowedLanguages }, testCases: cases.map(testCase => ({ id: testCase._id, input: testCase.input, expectedOutput: testCase.expectedOutput, isHidden: testCase.isHidden })) }); });
export const createProblem = asyncHandler(async (req, res) => { const input = createInput.parse(req.body); const { meeting, member } = await context(req.params.meetingCode, req.user._id); if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!host(member)) return res.status(403).json({ message: 'Interviewer permission required.' }); if (['ENDED', 'CANCELLED', 'EXPIRED'].includes(meeting.status) || meeting.technical?.candidateStartedAt) return res.status(409).json({ message: 'Problems cannot be changed after coding has started.' }); const existing = await Problem.find({ meetingId: meeting._id }).select('timeLimitSec').lean(); const durationSec = existing.reduce((total, problem) => total + problem.timeLimitSec, input.timeLimitSec); if (durationSec > 14400) return res.status(400).json({ message: 'Total coding time cannot exceed four hours.' }); const problem = await Problem.create({ ...input, testCases: undefined, meetingId: meeting._id, order: existing.length }); await TestCase.insertMany(input.testCases.map((testCase, index) => ({ ...testCase, problemId: problem._id, order: index }))); Object.assign(meeting.technical, { durationSec, ready: false, problemVisible: false, codingAccess: false }); await meeting.save(); res.status(201).json({ problem: { id: problem._id, title: problem.title } }); });

const executionInput = z.object({ language: z.enum(['javascript', 'python', 'cpp']), sourceCode: z.string().min(1).max(100000), action: z.enum(['run', 'submit']) });
const normalize = (value) => String(value ?? '').replace(/\r\n/g, '\n').trimEnd();
export const executeProblem = asyncHandler(async (req, res) => {
  const input = executionInput.parse(req.body); const { meeting, member } = await context(req.params.meetingCode, req.user._id);
  if (!meeting) return res.status(404).json({ message: 'Technical interview not found.' }); if (!member) return res.status(403).json({ message: 'Meeting approval is required.' });
  if (!['LIVE', 'PAUSED'].includes(meeting.status)) return res.status(409).json({ message: 'Code can be executed only during an active interview.' });
  if (!host(member) && !meeting.technical?.problemVisible) return res.status(403).json({ message: 'The interviewer has not revealed this problem yet.' });
  if (!host(member) && !meeting.technical?.candidateStartedAt) return res.status(409).json({ message: 'Click Start coding before running or submitting code.' });
  if (!host(member) && meeting.technical?.roundEndedAt) return res.status(409).json({ message: 'The coding round has ended.' });
  if (!host(member) && (!meeting.technical?.codingAccess || meeting.technical?.candidateId?.toString() !== req.user._id.toString())) return res.status(409).json({ message: 'Camera, microphone and screen sharing must remain active while coding.' });
  if (!host(member) && meeting.technical?.candidateStartedAt && Date.now() >= new Date(meeting.technical.candidateStartedAt).getTime() + (meeting.technical.durationSec ?? 0) * 1000) return res.status(410).json({ message: 'The coding time limit has ended.' });
  const problem = await Problem.findOne({ _id: req.params.problemId, meetingId: meeting._id }); if (!problem) return res.status(404).json({ message: 'Problem not found.' });
  if (!problem.allowedLanguages.includes(input.language)) return res.status(400).json({ message: 'This language is not allowed for the problem.' });
  if (!host(member) && await Submission.exists({ meetingId: meeting._id, problemId: problem._id, candidateId: req.user._id, action: 'submit' })) return res.status(409).json({ message: 'This solution was already submitted and is read-only.' });
  const candidateId = req.user._id.toString(); const room = `code:${meeting._id}:${problem._id}:${input.language}:${candidateId}`; const io = req.app.get('io');
  const activity = (status, extra = {}) => { if (!host(member)) io?.to(room).emit('code:activity', { candidateId, action: input.action, status, ...extra }); };
  if (!host(member)) await CandidateDraft.findOneAndUpdate({ meetingId: meeting._id, problemId: problem._id, candidateId, language: input.language }, { $set: { sourceCode: input.sourceCode } }, { upsert: true, setDefaultsOnInsert: true });
  activity(input.action === 'run' ? 'RUNNING' : 'SUBMITTING');
  const tests = await TestCase.find({ problemId: problem._id }).sort({ order: 1 }).lean();
  const results = [];
  try { for (const testCase of tests) { const run = await executeInSandbox({ language: input.language, sourceCode: input.sourceCode, stdin: testCase.input }); results.push({ passed: !run.compileError && !run.stderr && normalize(run.stdout) === normalize(testCase.expectedOutput), run, sample: !testCase.isHidden, expectedOutput: testCase.expectedOutput }); } }
  catch (error) { activity('FAILED'); throw error; }
  if (!host(member)) { const current = await Meeting.findById(meeting._id).select('technical status').lean(); const deadline = new Date(current.technical.candidateStartedAt).getTime() + current.technical.durationSec * 1000; if (current.technical.roundEndedAt || Date.now() >= deadline || !['LIVE', 'PAUSED'].includes(current.status)) { activity('FAILED'); return res.status(410).json({ message: 'The coding time limit has ended.' }); } if (await Submission.exists({ meetingId: meeting._id, problemId: problem._id, candidateId: req.user._id, action: 'submit' })) { activity('FAILED'); return res.status(409).json({ message: 'This problem already has a final submission.' }); } }
  const passed = results.filter(result => result.passed).length; const firstFailure = results.find(result => !result.passed); let submission;
  try { submission = await Submission.create({ meetingId: meeting._id, problemId: problem._id, candidateId: req.user._id, ...(input.action === 'submit' ? { finalKey: `${meeting._id}:${problem._id}:${req.user._id}` } : {}), language: input.language, sourceCode: input.sourceCode, action: input.action, status: firstFailure?.run.compileError || firstFailure?.run.stderr ? 'failed' : 'completed', testSummary: { passed, total: tests.length }, visibleResult: firstFailure ? { stdout: firstFailure.run.stdout, stderr: firstFailure.run.stderr, compileError: firstFailure.run.compileError, runtimeMs: firstFailure.run.runtimeMs } : {} }); }
  catch (error) { if (error.code === 11000 && input.action === 'submit') return res.status(409).json({ message: 'This problem already has a final submission.' }); throw error; }
  const summary = { passed, total: tests.length };
  activity(input.action === 'run' ? 'RUN_COMPLETE' : 'SUBMITTED', { summary });
  if (input.action === 'submit' && !host(member)) {
    const [problemCount, submittedCount] = await Promise.all([Problem.countDocuments({ meetingId: meeting._id }), Submission.countDocuments({ meetingId: meeting._id, candidateId, action: 'submit' })]);
    const roundEnded = submittedCount >= problemCount;
    let endedAt = null;
    if (roundEnded) { const ended = await Meeting.findOneAndUpdate({ _id: meeting._id, 'technical.roundEndedAt': null }, { $set: { 'technical.roundEndedAt': new Date(), 'technical.codingAccess': false } }, { new: true }); endedAt = ended?.technical.roundEndedAt ?? (await Meeting.findById(meeting._id).lean())?.technical?.roundEndedAt; if (ended) io?.to(`meeting:${meeting._id}`).emit('coding:ended', { candidateId, reason: 'submitted', endedAt }); }
    const sockets = await io?.in(`meeting:${meeting._id}`).fetchSockets() ?? [];
    sockets.filter(socket => socket.data.user.id === candidateId || host({ role: socket.data.role })).forEach(socket => socket.emit('code:submitted', { candidateId, problemId: problem._id.toString(), language: input.language, sourceCode: input.sourceCode, summary }));
    res.json({ submissionId: submission._id, status: submission.status, summary, submitted: true, roundEnded: Boolean(endedAt), endedAt, feedback: endedAt ? 'All problems submitted. Coding round ended.' : 'Problem submitted. You can continue with the remaining problems.' });
    return;
  }
  res.json({ submissionId: submission._id, status: submission.status, summary, submitted: input.action === 'submit', results: input.action === 'run' ? results.map(result => ({ passed: result.passed, isHidden: !result.sample, ...(result.sample ? { stdout: result.run.stdout, stderr: result.run.stderr, compileError: result.run.compileError, expectedOutput: result.expectedOutput } : { outcome: result.run.compileError ? 'Compilation error' : result.run.stderr ? 'Runtime error' : result.passed ? 'Passed' : 'Wrong answer' }) })) : undefined, feedback: input.action === 'submit' ? 'Solution submitted. Editing is now locked.' : undefined });
});
