import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../../lib/api';
import { useAuth } from '../auth/AuthProvider';

const blank = { title: '', description: '', type: 'normal', accessType: 'private', scheduledAt: '' };
export function Dashboard() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const [meetings, setMeetings] = useState([]); const [form, setForm] = useState(blank); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [joinCode, setJoinCode] = useState('');
  const change = key => event => setForm(current => ({ ...current, [key]: event.target.value }));
  const load = async () => { try { setMeetings((await api.get('/meetings')).data.meetings); } catch { setError('Could not load your meetings. Please refresh.'); } };
  useEffect(() => { load(); }, []);
  async function create(event) { event.preventDefault(); setBusy(true); setError(''); try { const payload = { ...form }; if (payload.scheduledAt) payload.scheduledAt = new Date(payload.scheduledAt).toISOString(); else delete payload.scheduledAt; const { data } = await api.post('/meetings', payload); setOpen(false); setForm(blank); navigate(data.joinPath); } catch (e) { setError(e.response?.data?.message ?? 'Could not create the meeting.'); } finally { setBusy(false); } }
  function join(event) { event.preventDefault(); const code = joinCode.trim().split('/').filter(Boolean).pop(); if (code) navigate(`/meetings/${code}`); }
  return <main className="dashboard"><nav><strong>Unified Interview</strong><div><span>{user?.name}</span><button onClick={async () => { await logout(); navigate('/auth'); }}>Sign out</button></div></nav><section className="dashboard-content"><div className="dashboard-heading"><div><p className="eyebrow">DASHBOARD</p><h1>Meet with purpose.</h1><p>Create, schedule, and manage your meetings before anyone joins.</p></div><button onClick={() => setOpen(true)}>+ Create meeting</button></div><section className="join-bar"><form onSubmit={join}><label>Join with a meeting link or code<input value={joinCode} onChange={e => setJoinCode(e.target.value)} placeholder="Paste a meeting link or code" /></label><button>Join</button></form></section>{error && <p className="error">{error}</p>}<section className="meeting-section"><h2>Your meetings</h2>{meetings.length === 0 ? <div className="empty-state"><strong>No meetings yet</strong></div> : <div className="meeting-grid">{meetings.map(({ meeting, role }) => <button className="meeting-card" key={meeting._id} onClick={() => navigate(`/meetings/${meeting.meetingCode}`)}><span className="badge">{meeting.type === 'technical_interview' ? 'Technical interview' : 'Normal meeting'}</span><h3>{meeting.title}</h3><p>{meeting.scheduledAt ? new Date(meeting.scheduledAt).toLocaleString() : 'Start anytime'} · {meeting.accessType}</p><small>{role}</small></button>)}</div>}</section></section>{open && <div className="modal-backdrop"><form className="modal" onSubmit={create}><div className="modal-title"><div><p className="eyebrow">NEW SESSION</p><h2>Create a meeting</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)}>×</button></div><label>Title<input required minLength="3" value={form.title} onChange={change('title')} /></label><label>Description<textarea value={form.description} onChange={change('description')} /></label><label>Session type<select value={form.type} onChange={change('type')}><option value="normal">Normal meeting</option><option value="technical_interview">Technical interview</option></select></label><label>Access<select value={form.accessType} onChange={change('accessType')}><option value="private">Private - approve participants</option><option value="public">Public - participants join directly</option></select></label><label>Schedule for (optional)<input type="datetime-local" value={form.scheduledAt} onChange={change('scheduledAt')} /></label><button disabled={busy}>{busy ? 'Creating...' : 'Create secure link'}</button></form></div>}</main>;
}
