import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../../lib/api';

export function PreJoinPage() {
  const { meetingCode } = useParams(); const navigate = useNavigate(); const videoRef = useRef(null); const streamRef = useRef(null);
  const [state, setState] = useState({ loading: true, error: '', meeting: null, membership: null }); const [deviceError, setDeviceError] = useState(''); const [previewing, setPreviewing] = useState(false); const [cameraOn, setCameraOn] = useState(true); const [micOn, setMicOn] = useState(true); const [notice, setNotice] = useState(''); const [requests, setRequests] = useState([]);
  const load = async () => { try { const { data } = await api.get(`/meetings/by-code/${meetingCode}`); setState({ loading: false, ...data, error: '' }); } catch (e) { setState({ loading: false, error: e.response?.data?.message ?? 'Could not load meeting.' }); } };
  useEffect(() => { load(); return () => streamRef.current?.getTracks().forEach(track => track.stop()); }, [meetingCode]);
  useEffect(() => { if (videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current; }, [previewing]);
  async function startPreview() { try { setDeviceError(''); const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); streamRef.current = stream; setPreviewing(true); setCameraOn(true); setMicOn(true); setTimeout(() => { if (videoRef.current) videoRef.current.srcObject = stream; }, 0); } catch { setDeviceError('Camera or microphone access was blocked. You can still request access or join with devices off.'); } }
  function toggle(kind) { const enabled = kind === 'video' ? !cameraOn : !micOn; streamRef.current?.getTracks().filter(track => track.kind === kind).forEach(track => { track.enabled = enabled; }); if (kind === 'video') setCameraOn(enabled); else setMicOn(enabled); }
  async function join() { try { if (meeting.accessType === 'public') await api.post(`/meetings/by-code/${meetingCode}/join`); navigate(`/rooms/${meetingCode}`); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not join meeting.'); } }
  async function requestAccess() { try { const { data } = await api.post(`/meetings/by-code/${meetingCode}/request-access`); setNotice(data.message); await load(); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not request access.'); } }
  async function loadRequests() { try { const { data } = await api.get(`/meetings/by-code/${meetingCode}/join-requests`); setRequests(data.requests); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not load access requests.'); } }
  async function decide(requestId, decision) { try { await api.post(`/meetings/by-code/${meetingCode}/join-requests/${requestId}/decision`, { decision }); setRequests(items => items.filter(item => item.id !== requestId)); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not update the request.'); } }
  if (state.loading) return <main className="loading">Loading meeting...</main>; if (state.error) return <main className="prejoin"><Link to="/dashboard">← Back to dashboard</Link><h1>{state.error}</h1></main>;
  const { meeting, membership } = state; const isHost = membership?.role === 'host' || membership?.permissions?.canManageParticipants; const canJoin = meeting.accessType === 'public' || membership?.status === 'approved';
  return <main className="prejoin"><Link to="/dashboard">← Back to dashboard</Link><div className="prejoin-layout"><section><p className="eyebrow">{meeting.type === 'technical_interview' ? 'TECHNICAL INTERVIEW' : 'MEETING'}</p><h1>{meeting.title}</h1><p>{meeting.description || 'No description provided.'}</p><p className="share-link">Share link: <code>{window.location.href}</code></p></section><section className="device-card"><div className="video-preview">{previewing ? <video ref={videoRef} autoPlay muted playsInline /> : <div className="video-placeholder">Camera preview is off</div>}</div><div className="device-controls"><button type="button" className="secondary" onClick={startPreview}>{previewing ? 'Restart preview' : 'Test camera and microphone'}</button>{previewing && <><button type="button" className="secondary" onClick={() => toggle('video')}>{cameraOn ? 'Camera on' : 'Camera off'}</button><button type="button" className="secondary" onClick={() => toggle('audio')}>{micOn ? 'Microphone on' : 'Microphone off'}</button></>}</div>{deviceError && <p className="error">{deviceError}</p>}</section></div><section className="prejoin-card"><div><span className="status-dot" /> {meeting.accessType === 'private' ? 'Private access' : 'Public access'}</div><p>{membership?.status === 'pending' ? 'Your access request is awaiting host approval.' : canJoin ? 'You are ready to join.' : 'Request host approval to enter this private meeting.'}</p>{canJoin ? <button onClick={join}>Join meeting room</button> : <button onClick={requestAccess} disabled={membership?.status === 'pending'}>{membership?.status === 'pending' ? 'Request pending' : 'Request access'}</button>}{notice && <p className="notice">{notice}</p>}</section>{isHost && <section className="host-requests"><div><h2>Waiting room</h2><button className="secondary" onClick={loadRequests}>Refresh requests</button></div>{requests.length === 0 ? <p>No pending access requests.</p> : requests.map(request => <div className="request-row" key={request.id}><span><strong>{request.user.name}</strong><small>{request.user.email}</small></span><span><button onClick={() => decide(request.id, 'approved')}>Approve</button><button className="reject" onClick={() => decide(request.id, 'rejected')}>Reject</button></span></div>)}</section>}</main>;
}
