import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../../lib/api';
import { TechnicalWorkspace } from './TechnicalWorkspace';

export function PreJoinPage() {
  const { meetingCode } = useParams(); const navigate = useNavigate(); const videoRef = useRef(null); const streamRef = useRef(null); const [state, setState] = useState({ loading: true }); const [notice, setNotice] = useState(''); const [requests, setRequests] = useState([]); const [previewing, setPreviewing] = useState(false); const [edit, setEdit] = useState(null);
  const load = async () => { try { const { data } = await api.get(`/meetings/by-code/${meetingCode}`); setState({ loading: false, ...data }); setEdit({ title: data.meeting.title, description: data.meeting.description || '', accessType: data.meeting.accessType, scheduledAt: data.meeting.scheduledAt ? new Date(data.meeting.scheduledAt).toISOString().slice(0, 16) : '' }); } catch (e) { setState({ loading: false, error: e.response?.data?.message ?? 'Could not load meeting.' }); } };
  useEffect(() => { load(); return () => streamRef.current?.getTracks().forEach(track => track.stop()); }, [meetingCode]);
  useEffect(() => { if (state.membership?.status !== 'pending') return; const refresh = setInterval(load, 3000); return () => clearInterval(refresh); }, [meetingCode, state.membership?.status]);
  useEffect(() => { if (videoRef.current && streamRef.current) videoRef.current.srcObject = streamRef.current; }, [previewing]);
  async function preview() { try { streamRef.current = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); setPreviewing(true); setTimeout(() => { if (videoRef.current) videoRef.current.srcObject = streamRef.current; }, 0); } catch { setNotice('Camera/microphone access was blocked.'); } }
  async function join() { try { if (meeting.accessType === 'public') await api.post(`/meetings/by-code/${meetingCode}/join`); navigate(`/rooms/${meetingCode}`); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not join meeting.'); } }
  async function requestAccess() { try { setNotice((await api.post(`/meetings/by-code/${meetingCode}/request-access`)).data.message); load(); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not request access.'); } }
  async function save(event) { event.preventDefault(); try { await api.patch(`/meetings/by-code/${meetingCode}`, { ...edit, scheduledAt: edit.scheduledAt ? new Date(edit.scheduledAt).toISOString() : null }); setNotice('Meeting details saved.'); load(); } catch (e) { setNotice(e.response?.data?.message ?? 'Could not save details.'); } }
  async function loadRequests() { try { setRequests((await api.get(`/meetings/by-code/${meetingCode}/join-requests`)).data.requests); } catch { setNotice('Could not load requests.'); } }
  async function decide(id, decision) { try { await api.post(`/meetings/by-code/${meetingCode}/join-requests/${id}/decision`, { decision }); setRequests(items => items.filter(item => item.id !== id)); } catch { setNotice('Could not update request.'); } }
  if (state.loading) return <main className="loading">Loading meeting...</main>; if (state.error) return <main className="prejoin"><Link to="/dashboard">← Back</Link><h1>{state.error}</h1></main>;
  const { meeting, membership } = state; const isHost = membership?.role === 'host' || membership?.permissions?.canManageParticipants; const canJoin = meeting.accessType === 'public' || membership?.status === 'approved';
  return <main className="prejoin"><Link to="/dashboard">← Back to dashboard</Link><div className="prejoin-layout"><section><p className="eyebrow">{meeting.type === 'technical_interview' ? 'TECHNICAL INTERVIEW' : 'MEETING'}</p><h1>{meeting.title}</h1><p>{meeting.description || 'No description provided.'}</p><p className="share-link">Share link: <code>{window.location.href}</code></p>{meeting.scheduledAt && <p><strong>Scheduled:</strong> {new Date(meeting.scheduledAt).toLocaleString()}</p>}</section><section className="device-card"><div className="video-preview">{previewing ? <video ref={videoRef} autoPlay muted playsInline /> : <div className="video-placeholder">Camera preview is off</div>}</div><button className="secondary" onClick={preview}>Test camera and microphone</button></section></div><section className="prejoin-card"><p>{membership?.status === 'pending' ? 'Your access request is awaiting host approval.' : canJoin ? 'You are ready to join.' : 'Request host approval to enter this private meeting.'}</p>{canJoin ? <button onClick={join}>Join meeting room</button> : <button onClick={requestAccess} disabled={membership?.status === 'pending'}>{membership?.status === 'pending' ? 'Request pending' : 'Request access'}</button>}{notice && <p className="notice">{notice}</p>}</section>{isHost && edit && <><section className="host-requests"><h2>Meeting settings</h2><form onSubmit={save}><label>Title<input value={edit.title} onChange={e => setEdit({ ...edit, title: e.target.value })} /></label><label>Description<textarea value={edit.description} onChange={e => setEdit({ ...edit, description: e.target.value })} /></label><label>Access<select value={edit.accessType} onChange={e => setEdit({ ...edit, accessType: e.target.value })}><option value="private">Private</option><option value="public">Public</option></select></label><label>Schedule<input type="datetime-local" value={edit.scheduledAt} onChange={e => setEdit({ ...edit, scheduledAt: e.target.value })} /></label><button>Save changes</button></form></section>{meeting.type === 'technical_interview' && <TechnicalWorkspace meetingCode={meetingCode} canManage problemVisible={meeting.technical?.problemVisible} onProblemRevealed={load} />}<section className="host-requests"><div><h2>Waiting room</h2><button className="secondary" onClick={loadRequests}>Refresh requests</button></div>{requests.map(request => <div className="request-row" key={request.id}><span><strong>{request.user.name}</strong><small>{request.user.email}</small></span><span><button onClick={() => decide(request.id, 'approved')}>Approve</button><button className="reject" onClick={() => decide(request.id, 'rejected')}>Reject</button></span></div>)}</section></>}</main>;
}
